version: "3.9"
services:
  pwe_db:
    image: postgres:15.4
    container_name: pwe_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:${DB_DATA}
    ports:
      - "${DB_EXPOSE_PORT}:5432"

  pwe_api:
    container_name: pwe_api
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/PWE
    restart: unless-stopped
    command: >
      bash -c "alembic upgrade head && python3 src/pwe/main.py"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      pwe_db:
        condition: service_healthy
